#!/usr/bin/env python3
"""
Sleek command-line internet speed test.

It measures:
  - latency with a few lightweight requests
  - download speed from streamed test bytes
  - upload speed by POSTing generated bytes

No third-party packages required.
"""

from __future__ import annotations

import argparse
import statistics
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Callable


BASE_URL = "https://speed.cloudflare.com"
CHUNK_SIZE = 256 * 1024
DEFAULT_HEADERS = {
    "User-Agent": "Mozilla/5.0 (compatible; PySpeedTest/1.0)",
    "Accept": "*/*",
    "Origin": BASE_URL,
    "Referer": f"{BASE_URL}/",
}
RESET = "\033[0m"
BOLD = "\033[1m"
DIM = "\033[2m"
CYAN = "\033[36m"
GREEN = "\033[32m"
MAGENTA = "\033[35m"
YELLOW = "\033[33m"
RED = "\033[31m"


@dataclass
class SpeedResult:
    label: str
    bytes_total: int
    seconds: float

    @property
    def mbps(self) -> float:
        return (self.bytes_total * 8) / self.seconds / 1_000_000


def supports_color() -> bool:
    return sys.stdout.isatty()


def paint(text: str, color: str) -> str:
    if not supports_color():
        return text
    return f"{color}{text}{RESET}"


def pretty_bytes(size: int) -> str:
    units = ["B", "KB", "MB", "GB"]
    value = float(size)
    for unit in units:
        if value < 1024 or unit == units[-1]:
            return f"{value:.1f} {unit}" if unit != "B" else f"{int(value)} {unit}"
        value /= 1024
    return f"{value:.1f} GB"


def bar(value: float, max_value: float, width: int = 28) -> str:
    filled = 0 if max_value <= 0 else round((value / max_value) * width)
    filled = max(0, min(width, filled))
    return paint("#" * filled, GREEN) + paint("-" * (width - filled), DIM)


def timed(label: str, fn: Callable[[], SpeedResult | list[float]]) -> SpeedResult | list[float]:
    print(f"{paint('>', CYAN)} {label}...", end="", flush=True)
    try:
        result = fn()
    except Exception:
        print(f" {paint('failed', RED)}")
        raise
    print(f" {paint('done', GREEN)}")
    return result


def open_request(req: urllib.request.Request, timeout: float):
    return urllib.request.urlopen(req, timeout=timeout)


def measure_latency(samples: int, timeout: float) -> list[float]:
    timings = []
    for _ in range(samples):
        req = urllib.request.Request(
            f"{BASE_URL}/__down?bytes=0",
            headers=DEFAULT_HEADERS,
            method="GET",
        )
        started = time.perf_counter()
        with open_request(req, timeout) as response:
            response.read(512)
        timings.append((time.perf_counter() - started) * 1000)
    return timings


def measure_download(size: int, timeout: float) -> SpeedResult:
    req = urllib.request.Request(
        f"{BASE_URL}/__down?bytes={size}",
        headers=DEFAULT_HEADERS,
        method="GET",
    )
    received = 0
    started = time.perf_counter()

    with open_request(req, timeout) as response:
        while True:
            chunk = response.read(CHUNK_SIZE)
            if not chunk:
                break
            received += len(chunk)

    elapsed = max(time.perf_counter() - started, 0.001)
    return SpeedResult("Download", received, elapsed)


class UploadBody:
    def __init__(self, size: int):
        self.remaining = size

    def read(self, amount: int = -1) -> bytes:
        if self.remaining <= 0:
            return b""
        if amount is None or amount < 0:
            amount = self.remaining
        amount = min(amount, self.remaining, CHUNK_SIZE)
        self.remaining -= amount
        return b"0" * amount


def measure_upload(size: int, timeout: float) -> SpeedResult:
    body = UploadBody(size)
    req = urllib.request.Request(
        f"{BASE_URL}/__up",
        data=body,
        method="POST",
        headers={
            **DEFAULT_HEADERS,
            "Content-Length": str(size),
            "Content-Type": "application/octet-stream",
        },
    )
    started = time.perf_counter()

    with open_request(req, timeout) as response:
        response.read(1024)

    elapsed = max(time.perf_counter() - started, 0.001)
    return SpeedResult("Upload", size, elapsed)


def print_header() -> None:
    title = "PY SPEED TEST"
    line = "=" * (len(title) + 10)
    print()
    print(paint(f"+{line}+", MAGENTA))
    print(paint(f"|     {title}     |", MAGENTA))
    print(paint(f"+{line}+", MAGENTA))
    print(paint("Real download/upload measurement from Cloudflare test endpoints.", DIM))
    print()


def print_results(latencies: list[float], download: SpeedResult, upload: SpeedResult) -> None:
    fastest = min(latencies)
    median = statistics.median(latencies)
    max_speed = max(download.mbps, upload.mbps, 1.0)

    print()
    print(paint("Results", BOLD))
    print(f"  Ping      {paint(f'{median:7.1f} ms', YELLOW)}  best {fastest:.1f} ms")
    print(
        f"  Down      {bar(download.mbps, max_speed)} "
        f"{paint(f'{download.mbps:7.2f} Mbps', GREEN)}  "
        f"{pretty_bytes(download.bytes_total)} in {download.seconds:.2f}s"
    )
    print(
        f"  Up        {bar(upload.mbps, max_speed)} "
        f"{paint(f'{upload.mbps:7.2f} Mbps', GREEN)}  "
        f"{pretty_bytes(upload.bytes_total)} in {upload.seconds:.2f}s"
    )
    print()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="A polished CLI speed test using Python standard library only."
    )
    parser.add_argument(
        "--download-mb",
        type=int,
        default=50,
        help="download test size in MB (default: 50)",
    )
    parser.add_argument(
        "--upload-mb",
        type=int,
        default=20,
        help="upload test size in MB (default: 20)",
    )
    parser.add_argument(
        "--ping-samples",
        type=int,
        default=4,
        help="number of latency samples (default: 4)",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=30,
        help="network timeout in seconds (default: 30)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    download_size = max(args.download_mb, 1) * 1024 * 1024
    upload_size = max(args.upload_mb, 1) * 1024 * 1024
    ping_samples = max(args.ping_samples, 1)

    print_header()

    try:
        latencies = timed(
            f"Checking latency ({ping_samples} samples)",
            lambda: measure_latency(ping_samples, args.timeout),
        )
        download = timed(
            f"Testing download ({pretty_bytes(download_size)})",
            lambda: measure_download(download_size, args.timeout),
        )
        upload = timed(
            f"Testing upload ({pretty_bytes(upload_size)})",
            lambda: measure_upload(upload_size, args.timeout),
        )
    except urllib.error.URLError as exc:
        print()
        print(paint("Network test failed.", RED))
        print(f"{paint('Reason:', BOLD)} {exc}")
        print("Check your internet connection, firewall, proxy, or try again with a larger --timeout.")
        return 1
    except KeyboardInterrupt:
        print()
        print(paint("Cancelled.", YELLOW))
        return 130

    print_results(latencies, download, upload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
